version: "3.7"
services:
  scraper:
    container_name: linden-honey-scraper
    image: lindenhoney/linden-honey-scraper:latest
    build: .
    ports:
      - 80:8080
    networks:
      - linden-honey-net

networks:
  linden-honey-net:
    driver: bridge
