application:
  scrapers:
    grob:
      base-url: http://www.gr-oborona.ru/
      retry:
        maxRetries: 5
        firstBackoff: 1s
        maxBackoff: 6s

server:
  port: 8080

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics

logging:
  level:
    com:
      github:
        lindenhoney: DEBUG
